FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    build-essential cmake wget git python3 python3-pip unzip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install numpy

WORKDIR /build
