set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Tina SDK toolchain path — update when SDK is available
set(TINA_SDK_PATH "$ENV{TINA_SDK_PATH}" CACHE PATH "Tina SDK root")
set(TOOLCHAIN_PREFIX "${TINA_SDK_PATH}/toolchain/bin/arm-openwrt-linux-gnueabi")

set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++")
set(CMAKE_AR "${TOOLCHAIN_PREFIX}-ar")
set(CMAKE_RANLIB "${TOOLCHAIN_PREFIX}-ranlib")
set(CMAKE_STRIP "${TOOLCHAIN_PREFIX}-strip")

set(CMAKE_FIND_ROOT_PATH "${TINA_SDK_PATH}/staging_dir")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
